do /csuna/home/richardd/marith/networks/new10.str 1

get pat /csuna/home/richardd/marith/patterns/EQ-ONE.pat

set param outputtolerance 100
set mode allcrit 1
set ecrit 0.0

log /csuna/home/richardd/marith/weights/one-of-n/equ2.log

get w /csuna/home/richardd/marith/weights/one-of-n/skew10-6.wts
ptrain
save w /csuna/home/richardd/marith/weights/one-of-n/equ10-6.wts
get w /csuna/home/richardd/marith/weights/one-of-n/skew10-7.wts
ptrain
save w /csuna/home/richardd/marith/weights/one-of-n/equ10-7.wts
get w /csuna/home/richardd/marith/weights/one-of-n/skew10-8.wts
ptrain
save w /csuna/home/richardd/marith/weights/one-of-n/equ10-8.wts
get w /csuna/home/richardd/marith/weights/one-of-n/skew10-9.wts
ptrain
save w /csuna/home/richardd/marith/weights/one-of-n/equ10-9.wts
get w /csuna/home/richardd/marith/weights/one-of-n/skew10-10.wts
ptrain
save w /csuna/home/richardd/marith/weights/one-of-n/equ10-10.wts
log -
q
y
